{{alias}}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block
block     = +block-as-image +handle-as-empty-document

{block}
a.alimama.cn
hm.baidu.com
.csbew.com
.icast.cn
.91adv.com
.acs86.com
.cbjs.baidu.com
.doubleclick.net
.baidu.com/cpro
.share.baidu.com
.atm.youku.com
.lstat.youku.com
.stat.youku.com
.dcads.sina.com.cn
.adsunion.com
.googlesyndication.com
807.tianya.cn
806.tianya.cn
cpro.baidustatic.com
.cnzz.com
ggmm777.com
images.sohu.com
.admaster.com.cn/i
.atm.youku.com/crossdomain.xml
.sina.com.cn/crossdomain.xml
.tudou.com/tdcm/adcontrol
.google-analytics.com/urchin
.cnbeta.com/.*\.js
img.cnbeta.com/[^/]*\.(gif|png|jpg)
da.feedsportal.com/.*\.img
.baifendian.com
.allyes.com
