{{alias}}
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

block     = +block-as-image +handle-as-empty-document
shop      = -crunch-all-cookies allow-popups
auto-https = +redirect{s@http://@https://@}

polipo = +forward-override{forward 127.0.0.1:8123} allow-all-cookies
polipo-direct = +forward-override{forward 127.0.0.1:8456} allow-all-cookies
goagent = +forward-override{forward 127.0.0.1:8087} allow-all-cookies
tor = +forward-override{forward-sock5 127.0.0.1:9050 .}
direct = +forward-override{forward .} -block
local = +forward-override{forward .} -block allow-popups allow-all-cookies
default = +forward-override{forward .}

{auto-https}
www.facebook.com:80
developer.android.com:80
twitter.com:80
blogger.com:80
twitter.com:80

{polipo-direct}
.apple.com
.mzstatic.com
.phobos.apple.com
.php.net

{goagent}
.blogspot.com
.appspot.com
.c.youtube.com
www.pandora.com/$
.pandora.com/radio
.t.co
.twitter.com:443
.twimg.com
.tweetdeck.com:443
.cloudfront.net
.typekit.net
bit.ly
ow.ly
.nodejitsu.com
.railstutorial.org
nodemanual.org
.nokogiri.org
.wordpress.com
.debian.org
.rcinet.ca
.slideshare.net
feeds.feedburner.com

{polipo}
.blogger.com
.golang.org
.businessweek.com
.igossip.com
.pixnet.net
.dropbox.com
.dw.de
rain.orgfree.com
vim.runpaint.org
.ivank.net
.mathjax.org
.tjholowaychuk.com
.huayuworld.org
.dwnews.com
.hidemyass.com
.sourceforge.net
check.torproject.org
.igfw.net
.chinagfw.org
.caonima.biz
.aboluowang.com
.pbwiki.com

{local}
127.
192.168.
localhost
.moode
.daogou.net
.douxiu.com
.moode.cn

{direct}
.channel.facebook.com
.ak.facebook.com
.taobao.com
.alipay.com
.dropbox.com:443
.airasia.com
.agoda.net
.google.com
.cmbchina.com

{+redirect{s@^http://[^/]*/url\?.*url=http%3A%2F%2F([^&]*).*@http://frd/http://$1@}}
.google.com/url

{+fast-redirects{check-decoded-url}}
frd/http://
{block}
