{{alias}}
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

fragile   = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
block     = +block-as-image +handle-as-empty-document
shop      = -crunch-all-cookies allow-popups fragile
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
auto-https = +redirect{s@http://@https://@}

goagent = +forward-override{forward 127.0.0.1:8087} allow-all-cookies
tor = +forward-override{forward-socks5t 127.0.0.1:9150 .} +client-header-filter{hide-tor-exit-notation}
polipo = tor
youtube = goagent fragile
#youtube = tor +add-header{Access-Control-Allow-Origin: https://www.youtube.com} +add-header{Access-Control-Allow-Credentials: true} +add-header{Timing-Allow-Origin: https://www.youtube.com}
local = +forward-override{forward .} -block shop allow-all-cookies
direct = local
default = +forward-override{forward .}

{fragile}
mail.google.com

{shop}
.ebates.cn
.carters.com
.coremetrics.com

{youtube}
.c.youtube.com
.googlevideo.com

{tor}
.onion
check.torproject.org
.liveleak.com
.mingpao.com
.mixpanel.com
talkx.l.google.com:5222
talk.google.com:5222
mtalk.google.com:5228
.html5rocks.com
.pack.google.com:80

{auto-https}
www.google.com.hk
www.facebook.com:80
developer.android.com:80
twitter.com:80
blogger.com:80
www.youtube.com:80
developer.chrome.com:80
code.google.com:80
youtu.be
webcache.googleusercontent.com

{polipo}
bit.ly
ow.ly
.nokogiri.org
.wordpress.com
.debian.org
.slideshare.net

.businessweek.com
.igossip.com
.pixnet.net
rain.orgfree.com
vim.runpaint.org
.ivank.net
.tjholowaychuk.com
.huayuworld.org
#.sourceforge.net
.pbwiki.com

.wordpress.com
polymer-project.org
.ptt.cc
.facebook.com:443
.nytimes.com
feeds.feedburner.com
developers.facebook.com
.ihid.co.uk
.iask.ca
.rcinet.ca
.dw.de
.dwnews.com
.hidemyass.com
.igfw.net
.chinagfw.org
.caonima.biz
trc.taboola.com
.aboluowang.com
.git-scm.com
.vimeo.com
.t.co
.twitter.com:443
.twimg.com
.tweetdeck.com:443
platform.twitter.com
.ck101.com
.tw.myblog.yahoo.com
.slideshare.net
.blogspot.com
.blogblog.com
.appspot.com

{goagent}
www.pandora.com/$
.pandora.com/radio

{local}
0.0.0.0
127.
192.168.
localhost
.douxiu.com
.moode.cn

{direct}
.xdf.cn
.jd.com
.hipandora.com
.dropbox.com:443
.airasia.com
.agoda.net
.cmbchina.com
#Taobao
.tbsandbox.com
.taobao.com
.alipay.com
.mmstat.com
.alimama.com
.10010.com

{block}
.tj.video.qq.com
.trace.qq.com
.pingfore.qq.com
.sns.video.qq.com
.l.qq.com
.tencentmind.com
.rcgi.video.qq.com
.aid.video.qq.com

tongji.zhidao.baidu.com
/.*stats.gif
.tanx.com
/player/.*pageer.swf
show.g.mediav.com
.ggxt.net
/.*preloader.swf
.admaster.com.cn
.51.la
.cookie4you.com
.miaozhen.com
a.alimama.cn
.csbew.com
.icast.cn
.91adv.com
.acs86.com
.cbjs.baidu.com
cpro.baidustatic.com
.baidu.com/cpro
.doubleclick.net
.atm.youku.com
.lstat.youku.com
.stat.youku.com
.dcads.sina.com.cn
.adsunion.com
.googlesyndication.com
807.tianya.cn
806.tianya.cn
.cnzz.com
ggmm777.com
images.sohu.com
.admaster.com.cn/i
.atm.youku.com/crossdomain.xml
.navi.youku.com/crossdomain.xml
.irs01.
.sina.com.cn/crossdomain.xml
.tudou.com/tdcm/adcontrol
.google-analytics.com/urchin
.cnbeta.com/.*\.js
img.cnbeta.com/[^/]*\.(gif|png|jpg)
da.feedsportal.com/.*\.img
.baifendian.com
.allyes.com
hm.baidu.com
