{{alias}}
+crunch-all-cookies = +crunch-incoming-cookies +crunch-outgoing-cookies
-crunch-all-cookies = -crunch-incoming-cookies -crunch-outgoing-cookies
 allow-all-cookies  = -crunch-all-cookies -session-cookies-only -filter{content-cookies}
 allow-popups       = -filter{all-popups} -filter{unsolicited-popups}
+block-as-image     = +block{Blocked image request.} +handle-as-image
-block-as-image     = -block

fragile   = -block -crunch-all-cookies -filter -fast-redirects -hide-referer -prevent-compression
block     = +block-as-image +handle-as-empty-document
shop      = fragile
allow-ads   = -block -filter{banners-by-size} -filter{banners-by-link}
auto-https = +redirect{s@http://@https://@}

mynet = +forward-override{forward 127.0.0.1:8080} allow-all-cookies fragile
goagent = +forward-override{forward 127.0.0.1:8087} allow-all-cookies
tor = +forward-override{forward-socks5t 127.0.0.1:9150 .} +client-header-filter{hide-tor-exit-notation}
polipo = tor
google = tor
local = +forward-override{forward .} -block shop allow-all-cookies
direct = local
default = +forward-override{forward .}
default = local

{fragile}
localhost
.google.com
.amazon.
amazoncustomerservice.d2.sc.omtrdc.net
paypal.com
paypal.d1.sc.omtrdc.net
.ecpic.com.cn
.cpic.
.images-amazon.com

{shop}
.360buyimg.com
.jd.com
.ebates.cn
.carters.com
.coremetrics.com
.tmall.com
.tbcdn.cn
.taobao.com
.tanx.com
.3.cn
.amazon.co.jp

{google}
.blogspot.com
.appspot.com
#.gorillatoolkit.org

{tor}
.onion
check.torproject.org
.liveleak.com
.mingpao.com
.mixpanel.com
.html5rocks.com
.nextmedia.com
.teepr.com
gist.github.com

{auto-https}
www.google.com.hk
www.facebook.com:80
developer.android.com:80
twitter.com:80
blogger.com:80
developer.chrome.com:80
code.google.com:80
webcache.googleusercontent.com
bit.ly:80

{polipo}
#bit.ly
ow.ly
.wordpress.com
.slideshare.net
.nextmedia.com
.businessweek.com
.pixnet.net
rain.orgfree.com
vim.runpaint.org
.ivank.net
.facebook.com
.dropbox.com

.wordpress.com
.ptt.cc
.ihid.co.uk
.iask.ca
.rcinet.ca
.hidemyass.com
.caonima.biz
trc.taboola.com
.vimeo.com
t.co
.twitter.com
medium.com
platform.twitter.com
.ck101.com
.slideshare.net
.instagram.com

{goagent}
www.pandora.com/$
.pandora.com/radio

{local}
0.0.0.0
127.
192.168.
localhost
.amap.com

{direct}
.japanpost.jp
.xdf.cn
.dropbox.com:443
.airasia.com
.agoda.net
.cmbchina.com
#Taobao
.tbsandbox.com
.taobao.com
.alipay.com
.mmstat.com
.alimama.com
.10010.com
.qq.com
.map.bdstatic.com
.stock.finance.sina.com.cn

{block}
#.cnbeta.com
#.tieba.baidu.com
.googleadservices.com
.googletagservices.com
.ifengimg.com/ifeng/sources
.ifengimg.com/mappa
tongji.zhidao.baidu.com
/.*stats.gif
.tanx.com
/player/.*pageer.swf
.mediav.com
.ggxt.net
/.*preloader.swf
.admaster.com.cn
.51.la
.cookie4you.com
.miaozhen.com
a.alimama.cn
.csbew.com
.icast.cn
.91adv.com
.acs86.com
.cbjs.baidu.com
cpro.baidustatic.com
.baidu.com/cpro
.dcads.sina.com.cn
.adsunion.com
807.tianya.cn
806.tianya.cn
.cnzz.com
ggmm777.com
images.sohu.com
.irs01.
#.cnbeta.com/.*\.js
#img.cnbeta.com/[^/]*\.(gif|png|jpg)
.baifendian.com
.allyes.com
hm.baidu.com
dup.baidustatic.com/js/os.js
